FROM dustynv/pytorch:2.7-r36.4.0-cu128-24.04

WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY requirements.txt ./
COPY docker/modules/onnxruntime_gpu-1.23.0-cp312-cp312-linux_aarch64-l4t-jp6-cu129.whl /tmp/
RUN pip3 install --no-cache-dir -r requirements.txt \
      --index-url https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com \
    && pip3 install --force-reinstall --no-deps /tmp/onnxruntime_gpu-1.23.0-cp312-cp312-linux_aarch64-l4t-jp6-cu129.whl \
    && rm /tmp/onnxruntime_gpu-1.23.0-cp312-cp312-linux_aarch64-l4t-jp6-cu129.whl
COPY app ./app
EXPOSE 5000
CMD ["python3", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5000"]
